# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3

# Mod Properties
mod_version=0.0.1+26.1.2
maven_group=me.danvb10.mtsr
archives_base_name=mtsr

# Dependencies
fabric_version=0.155.2+26.1.2
owo_version=0.13.0+26.1
modmenu_version=18.0.0
